apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: LoadBalancer  # Habilita IP externa
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761